name: Selenium E2E test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        run: mvn clean test

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
           allure_results: allure-results
           gh_pages: gh-pages
           allure_report: allure-report
           allure_history: allure-history

      - name: Check the allure reports
        run: ls -a

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Assets-to-Download
          path: allure-results
          retention-days: 5