name: Selenium E2E test

on: [ push ]

jobs:
  test:
    name: Build TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Test
        run: mvn clean test

      - name: Get Allure History
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          allure_results: allure-results












